export WORKING_DIR=$(pwd)
export S3_BUCKET="s3://geoglows-scratch" # S3 bucket to store the zarr files
export S3_ZARR_NAME="retrospective.zarr" # Name of the zarr file
export REGION_NAME="us-west-2" # AWS region name
export OTHER_INSTANCE="" # ID of the other EC2 instance
export ACCESS_KEY_ID="" # AWS access key ID
export SECRET_ACCESS_KEY="" # AWS secret access key
export AWS_LOG_GROUP_NAME="AppendWeekLog" # AWS CloudWatch log group name
export AWS_LOG_STREAM_NAME="EC2" # AWS CloudWatch log stream name